nguage: node_js
node_js:
- node
- '7'
script: node index.js
before_install:
- openssl --help
- openssl aes-256-cbc -K $encrypted_d060566ab9d3_key -iv $encrypted_d060566ab9d3_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
- whoami
- chmod 777 ~/.ssh
- sudo touch ~/.ssh/id_rsa
- ls -la ~
- echo -e "Host 120.25.227.28\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp index.js root@120.25.227.28:~/test
