nguage: node_js
sudo: enabled
dist: trusty
node_js:
- node
- '7'
script: node index.js
before_install:
# - openssl --help
# - su root
- touch ~/.ssh/id_rsa
- ls -la ~
- openssl aes-256-cbc -K $encrypted_d060566ab9d3_key -iv $encrypted_d060566ab9d3_iv
  -in id_rsa.enc -out ./depoly_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 ./depoly_rsa
- ssh-add ./deploy_rsa
# - whoami
# - chmod 777 ~/.ssh
# - sudo touch ~/.ssh/id_rsa
# - ls -la ~
- echo -e "Host 120.25.227.28\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
after_success:
- scp index.js root@120.25.227.28:~/test
